.TH MPLIST 1 dwm\-VERSION
.SH NAME
mplist \- add tracks to mpd playlists
.SH SYNOPSIS
.B mplist
mplist [<options>] <playlist> [<track>] [<track>] ...
.SH DESCRIPTION
Mplist is a utility for mpd. Add one or more tracks to an mpd playlist
<playlist> is obligatory. <track> is optional and will fallback to currently playing track
.SH OPTIONS
.TP
.B \-h
Specify mpd host to override environment variables
.TP
.B \-p
Specify mpd port to override environment variables
.TP
.B \-q
Quiet mode = suppress output
.SH SEE ALSO
.BR mpd (1),
.BR mpc (1)
